// Auto-generated by deploy script - 2026-02-23T16:15:35.966Z
export const CONTRACTS = {
  FHE_LOTTERY: '0x06aD51ff5dE731B9Ed3D7A32320Ce4f435b16604',
} as const;

// Primary network configuration (Sepolia with Zama FHEVM)
export const NETWORK = {
  name: 'sepolia',
  chainId: 11155111,
  rpcUrl: 'https://eth-sepolia.public.blastapi.io',
  blockExplorer: 'https://sepolia.etherscan.io',
} as const;

// Zama FHEVM contract addresses on Sepolia
export const ZAMA_CONTRACTS = {
  FHEVM_EXECUTOR: '0x92C920834Ec8941d2C77D188936E1f7A6f49c127',
  ACL: '0xf0Ffdc93b7E186bC2f8CB3dAA75D86d1930A433D',
  KMS_VERIFIER: '0xbE0E383937d564D7FF0BC3b46c51f0bF8d5C311A',
  INPUT_VERIFIER: '0xBBC1fFCdc7C316aAAd72E807D9b0272BE8F84DA0',
  DECRYPTION_ADDRESS: '0x5D8BD78e2ea6bbE41f26dFe9fdaEAa349e077478',
  RELAYER_URL: 'https://relayer.testnet.zama.org',
  GATEWAY_CHAIN_ID: 10901,
} as const;

// Entry fee in ETH
export const ENTRY_FEE = '0.001';

// Platform fee in basis points (0.3% = 30 bps)
export const PLATFORM_FEE_BPS = 30;
