const hre = require("hardhat");

async function main() {
  console.log("Deploying FHE Lottery V2 (with security fixes)...\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  
  const balance = await deployer.provider.getBalance(deployer.address);
  console.log("Account balance:", hre.ethers.formatEther(balance), "ETH");

  if (balance === 0n) {
    console.error("\n❌ No balance! Get testnet tokens from Zama faucet.");
    console.error("   Visit: https://faucet.zama.ai");
    process.exit(1);
  }

  // Use deployer as platform wallet for demo (change in production)
  const platformWallet = deployer.address;

  console.log("\nCompiling contracts...");
  const FHELottery = await hre.ethers.getContractFactory("FHELotteryV2");
  
  console.log("Deploying FHELotteryV2...");
  const lottery = await FHELottery.deploy(platformWallet);

  await lottery.waitForDeployment();

  const address = await lottery.getAddress();
  console.log("\n✅ FHE Lottery deployed to:", address);
  console.log("Platform wallet:", platformWallet);

  // Get initial round info
  const roundInfo = await lottery.getCurrentRound();
  console.log("\n📋 Initial Round Info:");
  console.log("  Round ID:", roundInfo.roundId.toString());
  console.log("  Start Time:", new Date(Number(roundInfo.startTime) * 1000).toISOString());
  console.log("  End Time:", new Date(Number(roundInfo.endTime) * 1000).toISOString());

  // Save deployment info
  const fs = require("fs");
  const deploymentInfo = {
    network: hre.network.name,
    contractAddress: address,
    platformWallet: platformWallet,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    constants: {
      entryFee: "0.001 ETH",
      roundDuration: "10 minutes",
      coolingPeriod: "10 minutes",
      maxPlayers: 60,
      maxNumber: 100,
      platformFeeBps: 30,
    },
  };

  fs.writeFileSync(
    "./deployment.json",
    JSON.stringify(deploymentInfo, null, 2)
  );
  console.log("\n💾 Deployment info saved to deployment.json");

  // Update frontend config
  const frontendConfigPath = "./frontend/src/config/contracts.ts";
  if (fs.existsSync("./frontend/src/config")) {
    const configContent = `// Auto-generated by deploy script - ${new Date().toISOString()}
export const CONTRACTS = {
  FHE_LOTTERY: '${address}',
} as const;

// Primary network configuration (Sepolia with Zama FHEVM)
export const NETWORK = {
  name: '${hre.network.name}',
  chainId: ${hre.network.config.chainId || 31337},
  rpcUrl: '${hre.network.name === 'sepolia' ? 'https://eth-sepolia.public.blastapi.io' : 'http://127.0.0.1:8545'}',
  blockExplorer: '${hre.network.name === 'sepolia' ? 'https://sepolia.etherscan.io' : ''}',
} as const;

// Zama FHEVM contract addresses on Sepolia
export const ZAMA_CONTRACTS = {
  FHEVM_EXECUTOR: '0x92C920834Ec8941d2C77D188936E1f7A6f49c127',
  ACL: '0xf0Ffdc93b7E186bC2f8CB3dAA75D86d1930A433D',
  KMS_VERIFIER: '0xbE0E383937d564D7FF0BC3b46c51f0bF8d5C311A',
  INPUT_VERIFIER: '0xBBC1fFCdc7C316aAAd72E807D9b0272BE8F84DA0',
  DECRYPTION_ADDRESS: '0x5D8BD78e2ea6bbE41f26dFe9fdaEAa349e077478',
  RELAYER_URL: 'https://relayer.testnet.zama.org',
  GATEWAY_CHAIN_ID: 10901,
} as const;

// Entry fee in ETH
export const ENTRY_FEE = '0.001';

// Platform fee in basis points (0.3% = 30 bps)
export const PLATFORM_FEE_BPS = 30;
`;
    fs.writeFileSync(frontendConfigPath, configContent);
    console.log("📝 Frontend config updated with deployed address");
  }

  console.log("\n🎰 FHE Lottery is ready!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
